### ISSUE TITLE
Question: Code structure / template

### ISSUE THREAD

**Issue by gogobd** [taesungp/contrastive-unpaired-translation#124]
Hi! I have a question about the code structure.

I really like the structure of this code base, i.e. the way options are handled, the directory / module structure etc. I have seen this structure across multiple projects in different pytorch experiments now and simply wanted to learn if there is some sort of "template" or example code base you were using.

**Comment by taesungp** [comment]
Hello @gogobd, the code structure is similar to [CycleGAN-pix2pix](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix), [SPADE](https://github.com/NVlabs/SPADE), and [Swapping Autoencoder](https://github.com/taesungp/swapping-autoencoder-pytorch). I don't have a template, but it's not too much work to strip away paper-specific codes. 

To use these codes as template, I recommend taking the code base of [Swapping Autoencoder](https://github.com/taesungp/swapping-autoencoder-pytorch), since that's the newest code, and modify [swapping_autoencoder_optimizer.py](https://github.com/taesungp/swapping-autoencoder-pytorch/blob/main/optimizers/swapping_autoencoder_optimizer.py), [swapping_autoencoder_model.py](https://github.com/taesungp/swapping-autoencoder-pytorch/blob/main/models/swapping_autoencoder_model.py). I usually find myself writing a new subclass of BaseDataset for data loading, and network structures under `models/networks/`. Please take a look at a brief explanation of the code structure [here](https://github.com/taesungp/swapping-autoencoder-pytorch#code-structure-main-functions).

**Comment by gogobd** [comment]
Thank you for sharing!
