### ISSUE TITLE
Error about multi-GPU training

### ISSUE THREAD

**Issue by ShawnBIT** [taesungp/contrastive-unpaired-translation#2]
Hi, thanks for the great work that can enable unpair image translation without the cycle mechanism. 

When I try to train the CUT model in a multi-GPU manner,  I just simply add the following code as you commented in line 212 of the file models/network.py
`net = torch.nn.DataParallel(net, gpu_ids)`

My training script is as follows.
`python train.py --dataroot ./datasets/toy_dataset --name my_CUT --CUT_mode CUT --gpu_ids 0,1,2,3,4,5,6,7 --batch_size 8 --load_size 512 --crop_size 512`

However, I encountered a type error as shown in the figure below. I am wondering how to solve the problem. Look forward to your reply.
![Error](https://user-images.githubusercontent.com/20378492/89094369-baa44f00-d3f5-11ea-8ff5-6e0a3ff0c69b.png)

**Comment by royee182** [comment]
Hi, I encountered the same problem.

The problem is due to the slicing of input data in data_dependent_initialize(). 
The modification in line 212 of the file models/network.py is needless.
Based on the official code, just add the following code in line 44 of train.py will work.

`model.set_input(data)`

**Comment by xuhaohao86** [comment]
@royee182 yes,you are right. Thanks

**Comment by taesungp** [comment]
Thank you for the suggestion. I added @royee182's commit in the newest commit. Also please note that we generally (and empirically) observe the best performance with batch size 1.
